### PR TITLE
Added Steps to Viscosity Calculator in Fluid Mechanics inside Classical Mechanics.

### PR DESCRIPTION
**Pull request by sinha-toyeesh**
## Related Issue

- Added Steps to Viscosity Calculator in Fluid Mechanics inside Classical Mechanics.

Fixes: #487

#### Describe the changes you've made

I have added the solution section to the viscosity calculator in classical mechanics.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **image** | <b>image </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@sinha-toyeesh rectify this
Screenshot (37)

**Comment by Amit366** [comment]
With just one value it should show error

**Comment by Amit366** [comment]
If u can rectify it now itself then fine else I will have to revert it

**Comment by sinha-toyeesh** [comment]
I'm fixing this , it happened because OR condition to check form filled instead of AND.

**Comment by sinha-toyeesh** [comment]
@Amit366 I have fixed the issue in PR #513

**Pull request merged**
