### PR TITLE
Static calculator bug sort

### PR DESCRIPTION
**Pull request by nik132-eng**
## Related Issue

- Info about Issue or bug

Fixes: #614 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
image

| **original screenshot** | <b>updated screenshot </b> |

image

### CODE REVIEW

**Comment by Amit366** [comment]
@nik132-eng what about the mode?

**Comment by Amit366** [comment]
And also u removed the package lock.json file

**Comment by nik132-eng** [comment]
for mode it give proper answers

**Comment by nik132-eng** [comment]
couldn't find any bug in that

**Comment by nik132-eng** [comment]
please check it out @Amit366  and thank you for your patience

**Comment by Amit366** [comment]
@nik132-eng why did u add the package-lock.json file outside the folder? I would suggest u to copy ur changes to the notepad and then again clone the repo and then make the changes.

**Comment by nik132-eng** [comment]
as you said I tried according to that but I got errors 

[remote: Permission to Tech-AND-Science/Fun with Science.git denied to nik 132-eng. fatal: unable to access 'https://github.com/Tech-N-Science/FunwithScience.git/': The requested URL returned error: 403](https://www.google.com/search?sxsrf=ALiCzsYTo1Y4xMPnczsjy5NHszkHuEwBNw:1652949757920&q=remote:+Permission+to+Tech-AND-Science/Fun+with+Science.git+denied+to+nik+132-eng.+fatal:+unable+to+access+%27https://github.com/Tech-N-Science/FunwithScience.git/%27:+The+requested+URL+returned+error:+403&spell=1&sa=X&ved=2ahUKEwiE1pvZlev3AhUzNaYKHTU3DosQkeECKAB6BAgBEDI)

than change in this branch only by deleting file.

**Comment by Amit366** [comment]
@nik132-eng did u fork the repo?

**Comment by nik132-eng** [comment]
yes sir of course. I already forked previously

**Comment by nik132-eng** [comment]
If the error is solved please merge it 😊

**Comment by Amit366** [comment]
@nik132-eng the problem is while deploying json files are important and since u have removed them so it's invalid. That's why I said to do this. 

> @nik132-eng why did u add the package-lock.json file outside the folder? I would suggest u to copy ur changes to the notepad and then again clone the repo and then make the changes.

**Comment by Amit366** [comment]
> as you said I tried according to that but I got errors
> 
> [remote: Permission to Tech-AND-Science/Fun with Science.git denied to nik 132-eng. fatal: unable to access 'https://github.com/Tech-N-Science/FunwithScience.git/': The requested URL returned error: 403](https://www.google.com/search?sxsrf=ALiCzsYTo1Y4xMPnczsjy5NHszkHuEwBNw:1652949757920&q=remote:+Permission+to+Tech-AND-Science/Fun+with+Science.git+denied+to+nik+132-eng.+fatal:+unable+to+access+%27https://github.com/Tech-N-Science/FunwithScience.git/%27:+The+requested+URL+returned+error:+403&spell=1&sa=X&ved=2ahUKEwiE1pvZlev3AhUzNaYKHTU3DosQkeECKAB6BAgBEDI)
> 
> than change in this branch only by deleting file.

This error occurs if try to change in the main repo.

**Pull request closed without merging**
