### PR TITLE
math ui improved

### PR DESCRIPTION
**Pull request by 03amir**
## Related Issue

--Change UI of math calculator

Fixes: #330
#### Describe the changes you've made

created a new array name ex stands for example for each topic. then rendering the array elements in the component. and returning it.

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :-------
Annotation 2022-02-06 232702
--------------: | :------------------------: |
| **original screenshot
Annotation 2022-02-06 2327024
** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
What is the change in UI? @03amir

**Comment by 03amir** [comment]
As the issue say to separate the process and example.

**Comment by Amit366** [comment]
@03amir but both the image look the same. Please share the updated screen shot

**Comment by 03amir** [comment]
Annotation 2022-02-06 232702

**Comment by Amit366** [comment]
@03amir u just added the heading. U needed to separate it in such a way that the example should start below the definition and cover entire row.

**Comment by 03amir** [comment]
ok

**Comment by Amit366** [comment]
Definition

@03amir like this

**Comment by 03amir** [comment]
Understood

**Pull request closed without merging**
