### PR TITLE
timer fixed

### PR DESCRIPTION
**Pull request by 03amir**
## Related Issue

-made the timer to the left corner and also don't display the timer at the score page.
Fixes: #344 

#### Describe the changes you've made

made the timer to the left also made it responsive

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by 03amir** [comment]
timerupdate

**Comment by Amit366** [comment]
Is the timer not visible on score page? @03amir

**Comment by 03amir** [comment]
yes. not showing on score page

**Comment by 03amir** [comment]
score update

**Pull request merged**
