### PR TITLE
Added Complex Number Calculator under Algebra section of Maths Module

### PR DESCRIPTION
**Pull request by KushalGhosh9899**
## Related Issue

- Info about Issue or bug

Fixes: #346 

#### Describe the changes you've made

I have added Complex Number calculator in Algebra section of maths. I have made changes in 'algebra.js' and 'Calculator.js' and 'Calculator.css' files under components/Algebra folder.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.- 
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

## Screenshots

|          Updated           |
Screenshot (288)
Screenshot (290)
Screenshot (291)
Screenshot (292)
Screenshot (293)

### CODE REVIEW

**Comment by KushalGhosh9899** [comment]
I have by mistakenly created two PRs in one Request. My second issue number was #332. I am Adding the Snapshots here

Original
Screenshot (298)

Updated
Screenshot (296)

Original
Screenshot (294)

Updated
Screenshot (295)

**Comment by Amit366** [comment]
@KushalGhosh9899 since u  have mixed both ur issues in one PR request you will get only one label, because I can't give two labels to one PR as the bot cannot identify it. So better send two PRs. If u r ok with one label then I can merge it.

And one more thing the explore button button make it similar to the learn button, the hover and the color.

**Comment by KushalGhosh9899** [comment]
Then is there any way to resolve this?

**Comment by KushalGhosh9899** [comment]
I am just trying to pushing my 2nd issue to my online forked repo but it automatically fetched in the pull request. Kindly help me

**Comment by Amit366** [comment]
@KushalGhosh9899 send a PR first after it gets merged then send the second

**Comment by KushalGhosh9899** [comment]
Explore button hover's issue is second issue. Please merge this commits first if possible, then I'll update explore button styling and send that in 2nd issue. Will that be ok?

**Pull request merged**
