### PR TITLE
unit tests for home and footers

### PR DESCRIPTION
**Pull request by sudeep162002**
## Related Issue

unit tests is required for checking codes regulerly

Fixes: unit tests

#### Describe the changes you've made

i have wrote test cases for home page and footer pages

## Checklist:

- [ *] My code follows the style guidelines of this project.
- [ *] I have performed a self-review of my own code.
- [ *] I have commented my code, particularly in hard-to-understand areas.
- [ *] I have made corresponding changes to the documentation.
- [ *] My changes generate no new warnings.

### CODE REVIEW

**Comment by Amit366** [comment]
@sudeep162002 u have completely deleted the package-lock.json file which creates problem.

**Comment by sudeep162002** [comment]
@Amit366 ok let me checque

**Comment by Amit366** [comment]
@sudeep162002 any update?

**Comment by sudeep162002** [comment]
can i close this pull request and create a new one??

**Comment by Amit366** [comment]
@sudeep162002 u can close this one and send another PR

**Pull request closed without merging**
