### PR TITLE
Added image for projectile motion

### PR DESCRIPTION
**Pull request by BabyElias**
The projectile motion page seemed underspecified due to lack of image to depict the concept visually.

Fixes: #563 

Uploaded image for projectile motion(no copyright associated,made it on my own in Paint 3D) in webp format. Couldn't add IT to the website as HTML codes are not visible.

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
Projectile motion

### CODE REVIEW

**Comment by Amit366** [comment]
@BabyElias u have added the image but u haven't added it in the website

**Comment by BabyElias** [comment]
@Amit366 Sir, I am unable to find the HTML file to the page.So, if you could guide me through it I will add the image to the website.

**Comment by Amit366** [comment]
@BabyElias there is no HTML file. Its done in react

**Comment by Amit366** [comment]
Go to classical mechanics folder and inside that calculator.js file

**Pull request closed without merging**
