### PR TITLE
Added Mathematical Induction Calculator

### PR DESCRIPTION
**Pull request by Nupur-Khatri**
Hello, 
I am a GSSOC-22 participant.
I have added Mathematical Induction theory and calculator in my branch. 
Fixes : - #577 
I request you to see the output i am providing here and please merge the branch into your project by accepting my pull request. 
image
image
image

### CODE REVIEW

**Comment by Nupur-Khatri** [comment]
Thank you , 
Hoping for the fruitful merge soon!!

**Comment by Amit366** [comment]
@Nupur-Khatri add the issue number

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri add the issue number

Hello , 
Sure , My issue number was - #577

**Comment by Amit366** [comment]
@Nupur-Khatri please follow the Pull request temple and add the issue number in its appropriate place. It should link to the issue. Checkout other one PR.

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri please follow the Pull request temple and add the issue number in its appropriate place. It should link to the issue. Checkout other one PR.

Hello, 
I have edited my PR as you said ..

**Comment by Amit366** [comment]
@Nupur-Khatri u have directly copied the definition from other websites. Please add ur own definition but u can take reference from other sites.

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri u have directly copied the definition from other websites. Please add ur own definition but u can take reference from other sites.

Hello,
Ok i will do the needful changes

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri u have directly copied the definition from other websites. Please add ur own definition but u can take reference from other sites.

Hello, 
I did the changes please have a look.

**Comment by Amit366** [comment]
@Nupur-Khatri the example section should be column wise as done in other calculators and also u haven't added the steps and error messages to the calculator

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri the example section should be column wise as done in other calculators and also u haven't added the steps and error messages to the calculator. If u can send the changes today then fine else I have to revert the PR

Hello, 
Thankyou for rewarding my work. 
I will add one another example to fill up the space as you said .. and also for the steps i will add for the steps for bernoulli calculator there, and in case of error message i have aldready added the error messages i.e. once anyone inputs wrong values they get the message the so and so thing is incorrectly inputed . 

image

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri the example section should be column wise as done in other calculators and also u haven't added the steps and error messages to the calculator. If u can send the changes today then fine else I have to revert the PR

Hello,

I did the edits you asked for .
Added steps 
image
And Edited the example column wise.
image

**Pull request merged**
