### PR TITLE
fixed ui math

### PR DESCRIPTION
**Pull request by 03amir**
## Related Issue

- Change UI of math calculator

Fixes: #330 

#### Describe the changes you've made

separate the example section from process and placed it in top of calculator

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by 03amir** [comment]
updated

**Comment by Amit366** [comment]
@03amir u r almost there but I said to cover the entire row. The 'Example' heading is a side heading.

**Comment by Amit366** [comment]
Definition

**Comment by Amit366** [comment]
U can write in this manner also

**Example**:  This is an example to demonstrate...........................

**Comment by 03amir** [comment]
update2

**Comment by 03amir** [comment]
ok now?

**Comment by Amit366** [comment]
Can U send the screen shot of another calculator whose example is quite big sentence @03amir

**Comment by Amit366** [comment]
But this fine as of now

**Comment by 03amir** [comment]
update3

**Comment by Amit366** [comment]
Screenshot (31)

@03amir What is this?

**Comment by Amit366** [comment]
You showed some screen shot but the something else is in practical.

**Comment by Amit366** [comment]
Screenshot (32)

**Pull request merged**
