### PR TITLE
Added AboutUs section

### PR DESCRIPTION
**Pull request by Aniket-508**
## Related Issue

- Info about Issue or bug

Fixes: #389 

#### Describe the changes you've made

Added a responsive about us section about Learn header.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
Screenshot (1)
Screenshot (2)

### CODE REVIEW

**Comment by Aniket-508** [comment]
@Amit366 Please review this!

**Comment by Amit366** [comment]
@Aniket-508 where have u taken the image from?

**Comment by Aniket-508** [comment]
From undraw and it copyright free. @Amit366

**Comment by Amit366** [comment]
@Aniket-508 can u add any other image. Are there any other options?

**Comment by Aniket-508** [comment]
Can you suggest some and then I will put it @Amit366 ? Because I thought it is calculator related, so I did put that image.

**Pull request merged**
