### PR TITLE
Issue #389  - About Us Page - Suvangi

### PR DESCRIPTION
**Pull request by Urstrulysuvangi**
## Create an About Page

- Created an about page as guided by the project maintainers. 

Fixes: #389 

#### Changes Made:

I made a separate section for the About Section as instructed by the project maintainers. I have used simple HTML and CSS to do this. I have taken reference from #414 in designing and building the section. I added a couple of pictures for enhancement purposes. All images used are copyright free.  Tried my best to maintain the responsiveness of the webpage. The pictures are attached below.

P.S. Please note I had to force install the node-modules due to version error/incompatibility

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

githubfunwithScience1
(Desktop View)

githubfunwithScience2
(Tablet View)

githubfunwithScience3
(Mobile View)

### CODE REVIEW

**Comment by Amit366** [comment]
@Urstrulysuvangi i said not to create another new page. U need to add it before the learn in the home page

**Comment by Amit366** [comment]
Rest everything is fine

**Comment by Urstrulysuvangi** [comment]
> @Urstrulysuvangi did u add it in a new page?

No I made the changes in the home.js (after the learn section, indicated by the comment : "About Us Section") and home.css files.

But as I mentioned before I did have to force install some modules due to version incompatibility so there are few changes seen in the package-lock.json, package.json and yarn.lock but I didn't intentionally change anything in them.

**Comment by Amit366** [comment]
@Urstrulysuvangi where have u taken the image from?

**Review by Amit366 — APPROVED** [review]

**Pull request merged**
