### PR TITLE
fix navbar to top

### PR DESCRIPTION
**Pull request by Amit91848**
## Related Issue

- Made the navbar fix to the top of the screen while scrolling

Fixes: #[358](https://github.com/Tech-N-Science/FunwithScience/issues/358)

#### Describe the changes you've made

Added a navbar class to `funwithphysics/src/Components/Navbar/Navbar.css`. Made the position fixed and increased z-index so that it remains at the top.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| Screenshot 2022-02-04 at 1 59 42 PM | Screenshot 2022-02-04 at 1 59 48 PM |

### CODE REVIEW

**Comment by Amit366** [comment]
@Amit91848 first of all remove the bracket from issue number and also when u hover over the plus sign of maths,physics and stay hovered for 3-4 seconds then u will be scrolled to top.

**Comment by Amit366** [comment]
@Amit91848 

https://www.loom.com/share/372a312acd564759a2e21347557b15fc

**Comment by Amit91848** [comment]
I tried but it is not happening for me

https://user-images.githubusercontent.com/74371312/152544833-baf8d44d-b26a-42df-90ae-9e263d80feef.mov

**Comment by Amit366** [comment]
@Amit91848 dm me on discord and then I will arrange a meet.

**Comment by Amit91848** [comment]
Okay

**Comment by Amit366** [comment]
@Amit91848 what are all these commits

**Comment by Amit366** [comment]
Send another PR with just one commit

**Pull request closed without merging**
