### PR TITLE
Added Steps to Pressure Calculator in Fluid Mechanics inside Classical Mechanics. 

### PR DESCRIPTION
**Pull request by Manik-Aggarwal**
## Related Issue

- Info about Issue or bug

Fixes: #[483]

#### Describe the changes you've made

Added Steps to Pressure Calculator in Fluid Mechanics inside Classical Mechanics.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original   
image
      |          Updated    
image
       |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by AnuragParashar2000** [comment]
@Amit366  I have checked this PR.

**Comment by Amit366** [comment]
Screenshot (38)
@Manik-Aggarwal without values it should show error message

**Comment by Amit366** [comment]
@Manik-Aggarwal send the modified PR

**Comment by Manik-Aggarwal** [comment]
ok @Amit366

**Pull request merged**
