### PR TITLE
Updating the icons in learn page

### PR DESCRIPTION
**Pull request by itzwow**
Updating the icons in learn page

#### Describe the changes you've made

changed the  icons  according the subjects

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
|
original
 | 
updating icons in learn
 |

### CODE REVIEW

**Comment by Amit366** [comment]
@itzwow the images might be copyright.

**Comment by Amit366** [comment]
And how can u send a PR without creating an issue?

**Comment by itzwow** [comment]
Hey! I am extremely sorry  :(

**Comment by itzwow** [comment]
> @itzwow the images might be copyright.

Attribution reqiured maybe so I if the changes are ok then I can add the attributes

**Comment by Amit366** [comment]
@itzwow since u haven't created an issue on this, so cannot accept

**Pull request closed without merging**
