### PR TITLE
Create contact.html

### PR DESCRIPTION
**Pull request by VIDHI-BAJAJ**
Merge this file in the contact.html page

Fixes: #[issue number #474 that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:
- [] My code follows the code style of this project.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@VIDHI-BAJAJ why did u create a new contact.html file? The contact us page is already present.

**Comment by VIDHI-BAJAJ** [comment]
@Amit366 As i was not finding any contact.html file i created the New on .if you say me where the file is i will add the correction in the file.

**Comment by Amit366** [comment]
U can find the file in components section, and then u can find contact folder

**Comment by Amit366** [comment]
@VIDHI-BAJAJ r u working?

**Comment by VIDHI-BAJAJ** [comment]
Yes ,I am working on it actually I am having my semester exams from 7 th so
it will take a bit time .

**Pull request closed without merging**
