### PR TITLE
Add solutions to the questions maths phy

### PR DESCRIPTION
**Pull request by Sampurankishoresrivastava**
## Related Issue

- Have to add solutions to the quiz.

Fixes: #[640]

#### Describe the changes you've made

I have added half maths quiz solution and half of the physics quiz solution.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: intial| :------------------------: after adding|
**original screenshot** | <b>updated screenshot </b> |
chnages

### CODE REVIEW

**Comment by Amit366** [comment]
@Sampurankishoresrivastava Heyy why did u send the screenshot of code? I can check ur code before merging, i asked u for the design on the website.

**Comment by Sampurankishoresrivastava** [comment]
Okay, I will attach the screenshot of my implementation on website.

**Comment by Amit366** [comment]
@Sampurankishoresrivastava for which questions have u added the solution for?

**Comment by Sampurankishoresrivastava** [comment]
Actually I have added the solution of the quiz, but I have realised that I had to add the solution of question section. Right now I am completing it, once done I will commit it and will pull request with the screenshot of the site. And sorry for the mistake, please buy me time till tomorrow.

**Pull request closed without merging**
