### PR TITLE
Thermal expansion

### PR DESCRIPTION
**Pull request by VATSAL-IIT**
## Related Issue

Issue:#491

Fixes: #491

#### Describe the changes you've made

Thermal Expansion Calculator added.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

image

image

### CODE REVIEW

**Comment by Amit366** [comment]
@VATSAL-IIT u haven't added the symbols to the input fields

**Comment by VATSAL-IIT** [comment]
Its now there

**Comment by Amit366** [comment]
@VATSAL-IIT I think u just sent it for the sake of sending a PR. Haven't u verified the calculator by inputing some values and checking?

**Comment by VATSAL-IIT** [comment]
I have checked that it works according to the formula only @Amit366

**Pull request merged**
