### PR TITLE
Updated Data.js by adding more relevant words .

### PR DESCRIPTION
**Pull request by AyushJain001**
Updated the FAQ section to make it more better.

## Related Issue

- Changed the contact us description by converting first letter to upper case and then added some more words to make it better.

Fixes: #538

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by AnuragParashar2000** [comment]
@AyushJain001 please provide some screenshots of your changes.

**Comment by AyushJain001** [comment]
> @AyushJain001 please provide some screenshots of your changes.

okay

**Comment by Amit366** [comment]
@AyushJain001 I had to revert this PR as the changes aren't being reflected on the website

**Comment by AyushJain001** [comment]
> @AyushJain001 I had to revert this PR as the changes aren't being reflected on the website

But It was looking fine in my system and changes was quite meaningful.
Kindly check once :)

**Pull request merged**
