### PR TITLE
Added periodic table to chemistry section

### PR DESCRIPTION
**Pull request by Samiksha-Garg**
## Related Issue

There was nothing under the topic chemistry. So added a section of periodic table and organic under it.

Fixes: #676 

#### Describe the changes you've made

First I changed "calculator" to "formula" under chemistry section. Added sections for periodic table and organic in it. Under periodic table added a periodic table with the functionality of seeing the property by clicking on the element.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

Original

Screenshot 2022-08-14 at 10 45 07 PM

Updated

Screenshot 2022-08-14 at 10 45 29 PM
Screenshot 2022-08-14 at 10 45 45 PM
Screenshot 2022-08-14 at 10 46 03 PM
Screenshot 2022-08-14 at 10 47 04 PM

P.S. For the data, I made use of https://github.com/Bowserinator/Periodic-Table-JSON
How and where to give credit?

### CODE REVIEW

**Comment by Amit366** [comment]
@Samiksha-Garg see on the top of Periodic table u can give a heading as 'periodic table " and below it in small font write the data is taken from https://github.com/Bowserinator/Periodic-Table-JSON

**Comment by Samiksha-Garg** [comment]
> @Samiksha-Garg see on the top of Periodic table u can give a heading as 'periodic table " and below it in small font write the data is taken from https://github.com/Bowserinator/Periodic-Table-JSON

So the credit will be visible on the screen under the heading, right?

**Comment by Amit366** [comment]
@Samiksha-Garg yes

**Comment by Samiksha-Garg** [comment]
Done!

**Review by Amit366 — APPROVED** [review]

**Pull request merged**
