### PR TITLE
fix: Added solution part for Ellipse and circle in Geometry section

### PR DESCRIPTION
**Pull request by KushalGhosh9899**
## Related Issue

- Added solution part for Ellipse and circle in Geometry section

Fixes: #511

#### Describe the changes you've made

Added solution part for different calculators in Geometry section -
- Ellipse
- Circle

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

https://user-images.githubusercontent.com/25982821/156884694-b1a28b34-ebf4-4666-bb6e-df762bddd28e.mp4

### CODE REVIEW

**Comment by Amit366** [comment]
Screenshot (40)
@KushalGhosh9899 here 8^2 is 8 only

**Comment by KushalGhosh9899** [comment]
It will be -2 the value of vertice 2 .. I'll update this on my next pr

**Comment by Amit366** [comment]
@KushalGhosh9899 and also thoda aur steps add karo ki a, b and c kaise nikla

**Comment by KushalGhosh9899** [comment]
should i show this on 3rd step itself?

**Comment by KushalGhosh9899** [comment]
should i show the calculations of a ,b in step 3rd itself @Amit366

**Comment by Amit366** [comment]
@KushalGhosh9899 putting all values ke baad add karna

**Comment by Amit366** [comment]
But a,b,c ka steps dikhana

**Pull request merged**
