### PR TITLE
Adding Editorial Page for math and physics section

### PR DESCRIPTION
**Pull request by HazemAbdo**
## Important Note 
* I install react-markdown to render markdown to html
## Related Issue
- Adding a page that contains a detailed solution and explanation for questions

* New files are *Editorial.js* which contains the react component, *editorialData.js* which contains mock-up data, and *Editorial.css* which contains the styling of the component.

* I Made a new component called *Editorial* which can be reused in any section.
The editorial component doesn't take any props put on the other hand it parse the question id and type from the URL.

* Based on the id and type it parses the needed editorial from the editorialData.js file. the content of any question is markdown format for reusability and to be easier to write the content in a systematic way.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] Handle case that the question has an editorial and  has no editorial
- [x] Make content in a markup language formate
### original
image
### New 
image

image

### CODE REVIEW

**Comment by Amit366** [comment]
@HazemAbdo i can see that u have made only one editorial page. So is it the same for math, physics and also quiz? And also u have removed the package-lock.json file.

**Comment by HazemAbdo** [comment]
> @HazemAbdo i can see that u have made only one editorial page. So is it the same for math, physics and also quiz? And also u have removed the package-lock.json file.

Yes, I made one editorial for math and physics and there is no need for making two different components.
If you can send a screenshot for the editorial of the quiz on the website if you get into the quiz section you will not find an editorial button.
In my repo there is a package-lock.json file in funWithScience and funWithPhysics directory and if you check the  funWithPhysics one you will see that I didn't remove it

**Comment by Amit366** [comment]
@HazemAbdo I got ur point but if u see the files changed here in this PR u can see that package lock is deleted

**Comment by HazemAbdo** [comment]
> @HazemAbdo I got ur point but if u see the files changed here in this PR u can see that package lock is deleted

man you are right I think It's due to my vscode settings so the file has limitations so It becomes 19797 instead of 40492 lines but literally I only add this line.so what we can do now?
image

**Comment by Amit366** [comment]
@HazemAbdo if it's ur settings then u only have to change it and again have to pull and then push.

**Comment by HazemAbdo** [comment]
> @HazemAbdo if it's ur settings then u only have to change it and again have to pull and then push.

I push a new commit to the branch with the updated package-lock.json file

**Comment by Amit366** [comment]
@HazemAbdo it showing error while installing react markdown

**Comment by Amit366** [comment]
@HazemAbdo for how many questions have u added the editorial for?

**Comment by HazemAbdo** [comment]
> @HazemAbdo for how many questions have u added the editorial for?

for the first two question in the math section

**Comment by HazemAbdo** [comment]
> @HazemAbdo it showing error while installing react markdown

can you share the error with me?

**Pull request merged**
