### PR TITLE
nav-bar and faq design changed

### PR DESCRIPTION
**Pull request by yaman-694**
## Related Issue

- Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@yaman-694 add working screenshot

**Comment by yaman-694** [comment]
screen shots 
Screenshot (1)
Screenshot (2)
Screenshot (3)

with site and code

**Comment by Amit366** [comment]
Because as of now it's the same only

**Review by AnuragParashar2000 — COMMENTED** [review]
You have changed the company name and the hover effect of the logo is not there. The navbar is also not fixed on scrolling. Please review the changes.

**Comment by yaman-694** [comment]
1) i have changed the aligment of the navbar option to between the navbar 
2) change to the font style of the logo and there is no change in hover if you want i can change back to default company logo.
3) i have made changes in the faq section of the and made some frontend changes.

if i have done any wrong please guide me its my first time 
thank you

**Comment by yaman-694** [comment]
orignal
image

updated
image


orignal
image

updated
image

**Pull request merged**
