### PR TITLE
Add steps for statistics calculator

### PR DESCRIPTION
**Pull request by LakshayN**
## Related Issue

- Info about Issue or bug

Fixes: #461 

#### Describe the changes you've made

I have added the steps for statistics calculator in algebra section.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| image | image  
image
|

### CODE REVIEW

**Comment by Amit366** [comment]
@LakshayN add working screenshot

**Comment by LakshayN** [comment]
@Amit366 check now. the first one is the original screenshot and the next two are working screenshot

**Comment by Amit366** [comment]
@LakshayN what have u done?
Add steps means, adding steps to the calculator and not to the process and formula.

**Comment by LakshayN** [comment]
> @LakshayN what have u done? Add steps means, adding steps to the calculator and not to the process and formula.

the calculator is already finding the mean, median, mode variance, st deviation, what more steps do i have to add ?

**Comment by Amit366** [comment]
If entered values are 2+3+4 then mean is 2+3+4/3. Like that. That's why I said to look at physics calculators.

**Comment by LakshayN** [comment]
im busy right now with other work, wont be able to work on it

**Pull request closed without merging**
