### PR TITLE
completed solution in circular motion

### PR DESCRIPTION
**Pull request by lakshrav**
## Related Issue
Add steps for circular motion calculator #460 

Fixes: #460 

Changes made:

-Added the solution section that appears on clicking calculate. Displays all inserted values, given values, formula, calculation and result.
- Corrected some typos in the working formula section.

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
|image

| <b>Screenshot 2022-04-04 at 4 23 03 PM
Screenshot 2022-04-04 at 4 22 35 PM
Screenshot 2022-04-04 at 4 22 23 PM
 </b> |

### CODE REVIEW

**Comment by lakshrav** [comment]
Please note - the last screenshot is not relevant

**Comment by lakshrav** [comment]
Please note - the last screenshot is not relevant. Added by mistake.

**Comment by Amit366** [comment]
@lakshrav issue number?

**Comment by lakshrav** [comment]
Issue number #460

**Comment by Amit366** [comment]
@lakshrav u need to mention it in issue template

**Pull request merged**
