### PR TITLE
Fixes #554

### LINKED ISSUE #554: Wrong Information in Torque Calculator
tempsnip
In the inertia tab , description has enter *force applied in Newtons*(kg-m/s2) but Inertia is the Moment of inertia of the body that is measured in kg-m2. 

There can be two ways to resolve this issue :
1) Add a *choose the object* form label, where we will have some standard objects/shapes(like disc,ring,cylinder,sphere,etc) whose 
   MOI will be automatically fetched by the website without having the user to enter it. And in case its not some standard shape but 
   the user knows the MOI, add a custom MOI tab for the user to enter.

2) Simply,just change the description of Inertia form label.

I am a GSSoC Contributor.Please assign me this issue and inform me about which option to consider.

### PR DESCRIPTION
**Pull request by BabyElias**
Changed description of labels in torque calculator
Fixes: #554 

#### Describe the changes you've made

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by AnuragParashar2000** [comment]
The Labels are fine now but please change the sign of torque(Tau), now the sign is: 
image
Earlier it was: 
image

**Comment by BabyElias** [comment]
ssnip
In the code segment I have changed, I hadn't made any changes to the symbol and even now, torque has tau as its label in the code. So, where to make this change of symbols?

**Comment by AnuragParashar2000** [comment]
@BabyElias  please attach a screenshot of your calculator.

**Comment by BabyElias** [comment]
Since the repo mainly contains all the JS files,so I am not able to deploy it as a website to view the calculator as a part of it.

**Pull request merged**
