### PR TITLE
Add steps and column wise example

### PR DESCRIPTION
**Pull request by Nupur-Khatri**
Hello,

fixes:- #577
I did the edits you asked for after the merge in #578  .

Added steps 
image
And Edited the example column wise.
image

### CODE REVIEW

**Comment by Amit366** [comment]
@Nupur-Khatri have u checked before sending the PR? Now the page is not opening

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri have u checked before sending the PR? Now the page is not opening

Yes I did .. and the screenshots I added were taken from the page only ..you can see the time as well in the screen shots .

**Comment by Amit366** [comment]
Screenshot (44)

@Nupur-Khatri then what is this?

**Comment by Nupur-Khatri** [comment]
> Screenshot (44)
> 
> @Nupur-Khatri then what is this?

Hello,
Oh I will see this issue today ... Will definitely resolve ...

**Comment by Amit366** [comment]
@Nupur-Khatri if u r facing any problem u can contact over discord

**Comment by Nupur-Khatri** [comment]
> @Nupur-Khatri if u r facing any problem u can contact over discord
Hello,
Edited changes are still visible on my device and also site is visible and working fine .. 
I am creating another pull request again you please try check there ..
image

**Pull request merged**
