### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by shivvamm**
updated screenshot
updated screenshot
## Related Issue

- Creating a new section in Relativity for Mass Variation or Relativistic Mass

Fixes: #497 

#### Describe the changes you've made

Things Done by me :
>Added the full definition in Relativisty.js of Mass Variation From the notes i created in 1st year on my own with the  formula and process keeping the process similar to the others format 
>Added the  Function name RelativeMASSCalculator in Calculator.js for whole calculation and finding result .
The calculation function was similar to the  time dilation so i take the reffrence from there as both has the same formula with slight change of mass and time 

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>original screenshot </b> |

### CODE REVIEW

**Comment by shivvamm** [comment]
Sorry i did'nt make the branch name understandable like for example Mass Variation  instead i make it Dev

**Comment by Amit366** [comment]
@shivvamm have u added the steps for the calculator?

**Comment by Amit366** [comment]
@shivvamm add the steps for the calculator and then send the PR

**Comment by shivvamm** [comment]
> @shivvamm add the steps for the calculator and then send the PR

Sir I already added the steps

**Comment by Amit366** [comment]
@shivvamm reset button is not clearing the result field

**Comment by shivvamm** [comment]
> @shivvamm reset button is not clearing the result field

Let me check it I did  created the reset as same as the others 
😅

**Comment by shivvamm** [comment]
sir its working perfect on my local server and the function is also proper 

https://user-images.githubusercontent.com/58168590/157642296-951d25f3-b82e-40a1-872b-cf50c6b3453b.mp4

**Pull request merged**
