### PR TITLE
feat: Add option to enter the angle value in radians

### PR DESCRIPTION
**Pull request by its-ayush-07**
## Related Issue

There was no option to enter the angle value in radians to calculate trigonometric functions

Fixes: #572 

#### Describe the changes you've made

Added an **option to select the unit (i.e. degree or radian)** of the angle and calculate the result accordingly

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### Original

#572_original

### Updated

#572_modified

### CODE REVIEW

**Review by Amit366 — CHANGES_REQUESTED** [review]
@its-ayush-07 actually u needed to add the radian functionality also.

**Comment by its-ayush-07** [comment]
> @its-ayush-07 actually u needed to add the radian functionality also.

What do you mean by radian functionality? Do you mean a separate input field to accept the angle value in radians? Please elaborate.

**Comment by Amit366** [comment]
@its-ayush-07 see now it accepts only degree values.  So add the radian functionality means when the user clicks on radian button then the given degree values will be converted and the result will be in radian.

**Comment by its-ayush-07** [comment]
> @its-ayush-07 see now it accepts only degree values. So add the radian functionality means when the user clicks on radian button then the given degree values will be converted and the result will be in radian.

Screenshot 2022-08-09 112817

On clicking the `Calculate` button, the value of angle(in radians) and the selected trigonometric function is being calculated.
Please review it once before I push the changes :)

**Comment by Amit366** [comment]
> > @its-ayush-07 see now it accepts only degree values. So add the radian functionality means when the user clicks on radian button then the given degree values will be converted and the result will be in radian.
> 
> Screenshot 2022-08-09 112817
> 
> On clicking the `Calculate` button, the value of angle(in radians) and the selected trigonometric function is being calculated. Please review it once before I push the changes :)

@its-ayush-07 it's fine

**Review by Amit366 — APPROVED** [review]

**Pull request merged**
